"use client";

import { useEffect, useRef, useState, type ReactNode, type FormEvent } from "react";
import { motion, useReducedMotion, AnimatePresence } from "framer-motion";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { ResponsiveImage as Photo } from "@/components/media/ResponsiveImage";
import { VideoPlayer } from "@/components/media/VideoPlayer";
import { ProjectGallery } from "@/components/ProjectGallery";
import { SafeReveal } from "@/components/SafeReveal";
import { useAnimationRuntime, scrollImmediately } from "@/hooks/useAnimationRuntime";
import { videoConfig } from "./media-config";
import { ArrowUpRight, ArrowDown, Check, Menu, MessageCircle, Phone, Sofa, CookingPot, DoorOpen, BedDouble, Plug, Lamp, Paintbrush, Layers, Blinds, Bath, Sparkles, Ruler, X } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Slider } from "@/components/ui/slider";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const phone = "919824734090";
const general = "Hello Shreeji Furniture, I am interested in a complete furniture/interior solution for my home. I would like to get an estimate.";
const whatsapp = (message = general) => `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;
const estimate = (home: string) => whatsapp(`Hello Shreeji Furniture, I would like an estimate for a ${home} complete furniture and turnkey interior solution. Please help me plan my home.`);

const nav = [["Our story", "about"], ["Services", "services"], ["Projects", "projects"], ["Packages", "packages"], ["Process", "process"]];
const packages = [
  { name: "2 BHK", range: "10–12", image: "package-2bhk.webp", title: "Small space. Beautiful possibilities.", description: "Intelligent storage, a practical kitchen and furniture that makes every corner count." },
  { name: "3 BHK", range: "13–15", image: "package-3bhk.webp", title: "More room for the life you love.", description: "A thoughtfully connected family home, from the welcoming living room to restful bedrooms." },
  { name: "4 BHK", range: "18–20", image: "package-4bhk.webp", title: "A home with your signature.", description: "Refined materials, custom furniture and considered details throughout a generous family home." }
];
const services = [
  ["Furniture", "Custom pieces, made for your space.", Sofa, "service-furniture.webp"],
  ["Modular Kitchen", "Practical layouts. Beautiful finishes.", CookingPot, "service-kitchen.webp"],
  ["Wardrobes", "A place for everything you love.", DoorOpen, "service-wardrobe.webp"],
  ["Beds", "Comfort, crafted around you.", BedDouble, "service-beds.webp"],
  ["Mattress", "The finishing touch to better rest.", Layers, "service-mattress.webp"],
  ["Electrical", "Thoughtful points and connections.", Plug, "service-electrical.webp"],
  ["Lighting", "The right mood in every room.", Lamp, "service-lighting.webp"],
  ["Painting", "Colours that bring it all together.", Paintbrush, "service-painting.webp"],
  ["False Ceiling", "A considered finish, overhead.", Layers, "service-ceiling.webp"],
  ["Curtains", "Privacy, texture and softer light.", Blinds, "service-curtains.webp"],
  ["Bathroom Accessories", "Everyday essentials, coordinated.", Bath, "service-bathroom.webp"],
  ["Interior Finishing", "Every final detail, taken care of.", Sparkles, "service-finishing.webp"]
] as const;
const steps = [["Consultation", "We listen to your requirements, style and budget."], ["Site Visit", "We measure your home and understand the space."], ["Design & Planning", "Furniture, kitchen, lighting and finishes come together."], ["Quotation", "You receive a defined scope and estimated budget."], ["Manufacturing", "Your custom furniture takes shape."], ["Interior Execution", "Installation, electrical work, ceiling and painting."], ["Final Setup", "Curtains, mattress, accessories and finishing touches."], ["Handover", "A complete home, ready for your next chapter."]];
const chapters = ["Empty home", "Planning", "Furniture", "Kitchen", "Electrical", "Lighting", "Ceiling", "Curtains", "Accessories", "Completed home"];
const chapterCopy = ["A blank canvas. A world of possibilities.", "Every measurement. Every material. One considered plan.", "Custom furniture makes the most of your space.", "A kitchen designed around everyday Indian living.", "Practical electrical points, planned from the start.", "Layered light brings warmth to every corner.", "A finished ceiling ties the room together.", "Soft textures. Privacy. Beautiful natural light.", "The small details that make a home feel yours.", "You bring the vision. We bring it all home."];

function Arrow(){ return <ArrowUpRight size={18} aria-hidden="true"/>; }
function CTA({children,href,className=""}:{children:ReactNode;href:string;className?:string}){return <a href={href} className={`button ${className}`}>{children}<Arrow/></a>}
const Reveal = SafeReveal;
function Heading({label,children,description}:{label:string;children:ReactNode;description?:string}){return <Reveal className="section-heading"><p className="eyebrow">{label}</p><h2>{children}</h2>{description&&<p className="section-description">{description}</p>}</Reveal>}

function Story(){
  const container=useRef<HTMLElement>(null);const [stage,setStage]=useState(0);const reduced=useReducedMotion();
  useEffect(()=>{
    if(reduced || !container.current)return;
    let ctx: ReturnType<typeof gsap.context> | undefined;
    try { gsap.registerPlugin(ScrollTrigger); ctx=gsap.context(()=>{
      ScrollTrigger.create({trigger:container.current,start:"top top",end:"bottom bottom",onUpdate:s=>setStage(Math.min(9,Math.floor(s.progress*10)))});
    },container); } catch(error) { console.warn("Transformation scroll unavailable; use the chapter buttons.",error); }
    return()=>ctx?.revert();
  },[reduced]);
  return <section ref={container} className={`story ${reduced?"reduced-story":""}`} aria-label="From empty home to completed home"><div className="story-sticky"><div className="story-intro"><div><p className="eyebrow">THE COMPLETE TRANSFORMATION</p><h2>One contractor.<br/><em>Everything covered.</em></h2></div><p>No juggling different contractors.<br/>One team takes care of every detail,<br/>from the first plan to the final curtain.</p></div><div className="story-visual"><AnimatePresence initial={false}>{<motion.div key={stage} className="story-frame" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:reduced?0:.65}}><Photo file={`story-${String(stage+1).padStart(2,"0")}.webp`} alt={`${chapters[stage]} — illustrative stage of a modern Ahmedabad home interior`} sizes="(max-width: 760px) 700px, 87vw"/></motion.div>}</AnimatePresence>
  <div className="story-vignette"/><div className="story-caption"><span className="story-number">{String(stage+1).padStart(2,"0")}<small> / 10</small></span><div><h3>{chapters[stage]}</h3><p>{chapterCopy[stage]}</p></div></div><span className="concept-tag">ILLUSTRATIVE TRANSFORMATION</span></div><div className="chapter-nav">{chapters.map((c,i)=><button key={c} className={i<=stage?"active":""} aria-pressed={stage===i} onClick={()=>{setStage(i);if(!reduced&&container.current){const top=window.scrollY+container.current.getBoundingClientRect().top;scrollImmediately(top+(container.current.offsetHeight-window.innerHeight)*(i+.25)/10)}}}><span>{String(i+1).padStart(2,"0")}</span>{c}</button>)}</div></div></section>
}
function BeforeAfter(){const [room,setRoom]=useState("Living Room");const [amount,setAmount]=useState(50);const file=room==="Living Room"?"living":room==="Bedroom"?"bedroom":"kitchen";return <section className="section transformation" id="transformation"><Heading label="A NEW CHAPTER FOR YOUR HOME" description="From an empty house to a complete home.">See the <em>transformation.</em></Heading><Tabs value={room} onValueChange={v=>{setRoom(v);setAmount(50)}}><TabsList className="room-tabs">{["Living Room","Bedroom","Kitchen"].map(r=><TabsTrigger key={r} value={r}>{r}</TabsTrigger>)}</TabsList>{["Living Room","Bedroom","Kitchen"].map(r=><TabsContent key={r} value={r}><div className="comparison"><Photo file={`comparison-${file}-after.webp`} sizes="(max-width: 760px) 700px, 87vw" alt={`Completed ${r.toLowerCase()} interior concept`}/><div className="before-layer" style={{clipPath:`inset(0 ${100-amount}% 0 0)`}}><Photo file={`comparison-${file}-before.webp`} sizes="(max-width: 760px) 700px, 87vw" alt={`Empty ${r.toLowerCase()} before interior work`}/></div><span className="comparison-label left">BEFORE</span><span className="comparison-label right">AFTER</span><div className="comparison-line" style={{left:`${amount}%`}}><span>〈 〉</span></div><Slider className="comparison-slider" value={[amount]} onValueChange={v=>setAmount(v[0])} min={0} max={100} step={1} aria-label={`${r} before and after comparison`}/></div></TabsContent>)}</Tabs><div className="comparison-foot"><span>Drag to discover the difference</span><span>Generated design concepts · Not completed client projects</span></div></section>}

export default function Home(){
 const reduced=useReducedMotion();const [menu,setMenu]=useState(false);const [home,setHome]=useState("3 BHK");const [property,setProperty]=useState("3 BHK");const [formStatus,setFormStatus]=useState("");const hero=useRef<HTMLElement>(null);
 useAnimationRuntime(hero, !!reduced);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const text=`Hello Shreeji Furniture, I would like a free consultation.\nName: ${String(data.get("name")).trim()}\nMobile: ${data.get("mobile")}\nLocation: ${String(data.get("location")).trim()}\nProperty: ${property}\nApproximate budget: ${data.get("budget")||"Please guide me"}\nMessage: ${String(data.get("message")||"").trim()}`;setFormStatus("Your details are ready. Send the message in WhatsApp to complete your request.");window.location.href=whatsapp(text)}
 return <><a href="#main" className="skip-link">Skip to content</a><header className="nav"><a className="brand" href="#" aria-label="Shreeji Furniture home">SHREEJI<span>FURNITURE & INTERIORS</span></a><nav aria-label="Main navigation">{nav.map(([label,id])=><a key={id} href={`#${id}`}>{label}</a>)}</nav><CTA href="#contact" className="nav-cta">Let’s talk</CTA><button className="menu-button" aria-label="Open navigation" onClick={()=>setMenu(true)}><Menu/></button></header>
 <Dialog open={menu} onOpenChange={setMenu}><DialogContent className="mobile-menu"><DialogTitle>Shreeji Furniture</DialogTitle><DialogDescription>Explore your complete home transformation.</DialogDescription>{nav.map(([label,id])=><a href={`#${id}`} key={id} onClick={()=>setMenu(false)}>{label}<Arrow/></a>)}<a href="#contact" onClick={()=>setMenu(false)}>Contact us<Arrow/></a></DialogContent></Dialog>
 <main id="main"><section className="hero" ref={hero}>{videoConfig.hero?<VideoPlayer source={videoConfig.hero} background className="hero-photo"/>:<Photo file="feature-hero.webp" alt="Representative Ahmedabad apartment interior with custom furniture, a TV unit, layered lighting and curtains" className="hero-photo" eager sizes="(max-width: 760px) 1500px, 100vw"/>}<div className="hero-shade"/><SafeReveal className="hero-copy" immediate><p className="eyebrow">THOUGHTFULLY MADE. COMPLETELY YOURS.</p><h1>From empty space<br/>to your <em>dream home.</em></h1><p>Complete Furniture & Turnkey Interior Solutions<br/>backed by 22+ years of craftsmanship.</p><div className="hero-actions"><CTA href="#contact">Get free estimate</CTA><a className="text-link" href="#projects">Explore our work<Arrow/></a></div></SafeReveal><div className="hero-bottom"><p>2 BHK <span>·</span> 3 BHK <span>·</span> 4 BHK <small>COMPLETE INTERIOR SOLUTIONS</small></p><a href="#about" className="scroll-link">SCROLL TO DISCOVER<ArrowDown size={16}/></a></div><div className="hero-side">CRAFTED WITH CARE. FINISHED WITH PRIDE.</div></section>
 <div className="trust-strip"><span><Check/>22+ years of experience</span><span><Check/>One point of contact</span><span><Check/>Custom-made for your home</span><span><Check/>From planning to handover</span></div>
 <section id="about" className="section about"><Reveal><p className="eyebrow">A HOUSE IS JUST THE BEGINNING</p><h2>You imagine a home.<br/>We take care of<br/><em>everything else.</em></h2></Reveal><Reveal className="about-copy"><p>Furniture. Kitchen. Electrical. Lighting. The final curtain. Bringing your home together shouldn’t mean bringing ten different contractors together.</p><p>Based in Ranip, Ahmedabad, Gujarat, Shreeji Furniture handles your complete home interior with 22+ years of hands-on craftsmanship and one simple promise: care in every detail. Serving Ahmedabad and nearby areas.</p><a className="underlined" href="#services">Discover our turnkey approach<Arrow/></a></Reveal></section>
 <Story/>
 <section className="section" id="services"><div className="heading-row"><Heading label="FROM THE BIG PICTURE TO THE LITTLE DETAILS">Everything your home needs.<br/><em>Under one roof.</em></Heading><p className="side-copy">One coordinated team.<br/>A beautifully connected home.</p></div><div className="services-grid">{services.map(([name,desc,Icon,img],i)=><Reveal key={name} className={`service-card service-${i}`}><a href={whatsapp(`Hello Shreeji Furniture, I would like to discuss ${name.toLowerCase()} for my home.`)}><Photo file={img} alt={`${name} — representative modern Indian home interior`} sizes="(max-width: 760px) 400px, (max-width: 1100px) 450px, 500px"/><div className="service-overlay"/><div className="service-top"><Icon size={23}/><Arrow/></div><div className="service-copy"><h3>{name}</h3><p>{desc}</p></div></a></Reveal>)}</div></section>
 <section className="section packages-section" id="packages"><Heading label="A BEAUTIFUL HOME. A CLEAR STARTING POINT." description="Complete furniture & turnkey interior solutions, planned around your home.">Complete home <em>packages.</em></Heading><div className="packages-grid">{packages.map((p,i)=><motion.article key={p.name} className={`package-card ${i===1?"featured":""}`} whileHover={reduced?{}:{y:-7,rotateX:1.5,rotateY:-1.5}} transition={{duration:.3}}>{i===1&&<span className="package-badge">THE FAMILY HOME</span>}<div className="package-image"><Photo file={p.image} alt={`${p.name} Ahmedabad apartment design inspiration`} sizes="(max-width: 760px) 86vw, 29vw"/><span>{p.name}</span></div><div className="package-body"><p className="eyebrow">TYPICAL STARTING RANGE</p><div className="price">₹{p.range}<span> Lakhs</span></div><h3>{p.title}</h3><p>{p.description}</p><ul><li><Check/>Custom furniture & storage</li><li><Check/>Kitchen, lighting & interior finishes</li><li><Check/>Coordinated end-to-end execution</li></ul><CTA href={estimate(p.name)} className={i===1?"":"outline"}>Get {p.name} estimate</CTA></div></motion.article>)}</div><p className="pricing-note">Final pricing depends on home size, design, materials, finishes and customization requirements. Detailed inclusions are confirmed in your quotation.</p></section>
 <BeforeAfter/>
 <ProjectGallery/>
 {videoConfig.work&&<section className="section work-video-section"><Heading label="CRAFTED IN AHMEDABAD" description="From workshop to final installation.">See our work <em>come together.</em></Heading><Reveal><VideoPlayer source={videoConfig.work}/></Reveal></section>}
 <section className="section process" id="process"><div className="process-intro"><Heading label="A SIMPLE JOURNEY. A COMPLETE HOME.">From our first hello<br/>to <em>your new home.</em></Heading><p>Clear steps. Personal attention.<br/>One team, all the way through.</p><CTA href={whatsapp("Hello Shreeji Furniture, I would like to schedule a site visit for my home. Please share your availability.")} className="outline">Schedule a site visit</CTA></div><div className="timeline">{steps.map(([title,desc],i)=><Reveal className="timeline-step" key={title}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{title}</h3><p>{desc}</p></div></Reveal>)}</div></section>
 <section className="experience" aria-labelledby="experience-heading"><Photo file="feature-craftsmanship.webp" alt="Sharp natural wood grain, joinery and furniture finishing detail" sizes="100vw"/><div className="experience-shade"/><Reveal className="experience-content"><p className="eyebrow">BUILT ON EXPERIENCE. FINISHED WITH CARE.</p><span className="experience-number">22<span>+</span></span><h2 id="experience-heading">Years of Furniture<br/>& Interior Experience</h2><p>Practical knowledge. Personal involvement.<br/>Craftsmanship that makes a house feel like home.</p></Reveal></section>
 <section className="section why"><Heading label="THE SHREEJI DIFFERENCE">Beautiful spaces.<br/><em>Dependable hands.</em></Heading><div className="why-grid">{[["22+ Years Experience","Decades of practical furniture and interior execution."],["Complete Turnkey Solution","One contractor manages your complete home."],["Custom Furniture","Furniture designed specifically for your available space."],["Practical Design","Beautiful designs that work for everyday Indian homes."],["Material Guidance","Help choosing suitable materials, finishes and colours."],["End-to-End Execution","From the first site visit to final home handover."]].map(([title,desc],i)=><Reveal className="why-card" key={title}><span>0{i+1}</span><h3>{title}</h3><p>{desc}</p></Reveal>)}</div></section>
 <section className="budget section"><div><p className="eyebrow">LET’S FIND YOUR STARTING POINT</p><h2>What type of home<br/>are you <em>planning?</em></h2></div><Tabs className="budget-control" value={home} onValueChange={setHome}><TabsList className="budget-tabs">{packages.map(p=><TabsTrigger key={p.name} value={p.name}>{p.name}</TabsTrigger>)}</TabsList>{packages.map(p=><TabsContent key={p.name} value={p.name}><p className="budget-range">Typical starting range<br/><strong>₹{p.range} Lakhs</strong></p><CTA href={estimate(p.name)}>Get your exact estimate on WhatsApp</CTA><p className="small-note">Final pricing varies by size, materials and scope.</p></TabsContent>)}</Tabs></section>
 <section className="section contact" id="contact"><div className="contact-copy"><Heading label="YOUR DREAM HOME STARTS WITH A CONVERSATION">Let’s build your<br/><em>dream home.</em></Heading><p>Tell us a little about your space.<br/>We’ll help you take the next step.</p><a className="contact-phone" href="tel:+919824734090">+91 98247 34090<Arrow/></a><p className="eyebrow">CALL OR WHATSAPP</p><div className="socials"><a href="https://www.instagram.com/ShreejiFurniture/" target="_blank" rel="noreferrer">Instagram<Arrow/></a><a href="https://www.facebook.com/ShreejiFurniture/" target="_blank" rel="noreferrer">Facebook<Arrow/></a></div><p className="small-note">@ShreejiFurniture<br/>Ranip, Ahmedabad, Gujarat<br/>Serving Ahmedabad and nearby areas.</p></div><form onSubmit={submit} className="contact-form"><div className="form-grid"><label>Your name<input name="name" placeholder="Full name" autoComplete="name" required minLength={2} maxLength={100} pattern={".*\\S.*"}/></label><label>Mobile number<input name="mobile" type="tel" inputMode="tel" autoComplete="tel" placeholder="10-digit mobile number" pattern="[6-9][0-9]{9}" title="Enter a valid 10-digit Indian mobile number" required/></label><label>Location<input name="location" placeholder="City / area" autoComplete="address-level2" minLength={2} maxLength={150} pattern={".*\\S.*"} required/></label><div><label id="property-label">Property type</label><Select value={property} onValueChange={setProperty}><SelectTrigger aria-labelledby="property-label" className="property-select"><SelectValue/></SelectTrigger><SelectContent>{["2 BHK","3 BHK","4 BHK","Other"].map(p=><SelectItem key={p} value={p}>{p}</SelectItem>)}</SelectContent></Select></div><label className="full">Approximate budget <span>(optional)</span><input name="budget" placeholder="e.g. ₹13–15 Lakhs" maxLength={100}/></label><label className="full">Tell us about your home <span>(optional)</span><textarea name="message" rows={3} placeholder="Your ideas, requirements or expected timeline…" maxLength={1500}/></label></div><button type="submit" className="button">Request free consultation<Arrow/></button><p className="small-note">Opens WhatsApp with your details. Review and send your message to request a consultation.</p><p role="status" className="form-status">{formStatus}</p><a className="underlined" href={whatsapp()}>Or chat on WhatsApp<MessageCircle size={18}/></a></form></section>
 </main><footer><div className="footer-main"><div><a className="brand" href="#">SHREEJI<span>FURNITURE & INTERIORS</span></a><p>Furniture & Interior Contractor<br/>Ranip, Ahmedabad, Gujarat<br/>22+ Years Experience</p><p>From an empty house.<br/>To a home that’s entirely yours.</p></div><div><h3>Explore</h3>{[["Home",""],["About","about"],...nav.slice(1),["Contact","contact"]].map(([label,id])=><a key={label} href={`#${id}`}>{label}</a>)}</div><div><h3>What we do</h3>{["Complete Home Furniture","Custom Furniture","Modular Kitchen","Bedroom Furniture","Wardrobes","TV Units","Interior Work","Turnkey Projects"].map(s=><a key={s} href="#services">{s}</a>)}</div><div><h3>Let’s connect</h3><a href="tel:+919824734090">+91 98247 34090</a><a href={whatsapp()}>WhatsApp<Arrow/></a><a href="https://www.instagram.com/ShreejiFurniture/" target="_blank" rel="noreferrer">Instagram<Arrow/></a><a href="https://www.facebook.com/ShreejiFurniture/" target="_blank" rel="noreferrer">Facebook<Arrow/></a><p>ShreejiFurniture</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Shreeji Furniture. All rights reserved.</span><span>Thoughtfully made. Completely yours.</span></div></footer><a className="floating-wa" href={whatsapp()} aria-label="Chat with Shreeji Furniture on WhatsApp"><MessageCircle size={26}/></a><div className="mobile-contact"><a href="tel:+919824734090"><Phone size={18}/>Call us</a><a href={whatsapp()}><MessageCircle size={18}/>WhatsApp</a></div></>
}
