import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
const source=path.resolve(process.argv[2]??'public/images/v2');
const output=path.resolve('public/images/v2');
await fs.mkdir(output,{recursive:true});
const names=(await fs.readdir(source)).filter(f=>/\.(png|jpe?g|webp)$/i.test(f)&&!/-\d+\.webp$/.test(f));
const manifest={};
for(const file of names){
 const key=file.replace(/\.[^.]+$/,'');const bytes=await fs.readFile(path.join(source,file));const meta=await sharp(bytes).metadata();
 if(!meta.width||!meta.height)throw Error(`Invalid image ${file}`);
 const widths=[...new Set([320,480,640,768,1024,1440,1672,1920,2560,3840].filter(w=>w<meta.width).concat(meta.width))].sort((a,b)=>a-b);
 // Never enlarge pixels. Native source retained at quality 94; smaller delivery files at 92.
 await sharp(bytes).webp({quality:94,effort:5}).toFile(path.join(output,key+'.webp'));
 for(const width of widths){await sharp(bytes).resize({width,withoutEnlargement:true}).webp({quality:92,effort:5}).toFile(path.join(output,`${key}-${width}.webp`));}
 manifest[key]={width:meta.width,height:meta.height,widths};
}
await fs.writeFile('components/media/image-manifest.ts','// Generated by scripts/prepare-media.mjs. Native dimensions; no upscaling.\nexport interface ImageRecord { width:number; height:number; widths:number[]; focal?:string; }\nexport const imageManifest: Record<string,ImageRecord> = '+JSON.stringify(manifest,null,2)+';\n');
console.log(`Prepared ${names.length} native images and responsive derivatives.`);
