// Generated by scripts/prepare-media.mjs. Native dimensions; no upscaling.
export interface ImageRecord { width:number; height:number; widths:number[]; focal?:string; }
export const imageManifest: Record<string,ImageRecord> = {
  "comparison-bedroom-after": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "comparison-bedroom-before": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "comparison-kitchen-after": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "comparison-kitchen-before": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "comparison-living-after": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "comparison-living-before": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "feature-craftsmanship": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "feature-hero": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "package-2bhk": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "package-3bhk": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "package-4bhk": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "project-2bhk": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "project-3bhk": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "project-4bhk": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "project-bathroom": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "project-bedroom": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "project-kitchen": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "project-tv": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "project-wardrobe": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "service-bathroom": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "service-beds": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "service-ceiling": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "service-curtains": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "service-electrical": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "service-finishing": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "service-furniture": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "service-kitchen": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "service-lighting": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "service-mattress": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "service-painting": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "service-wardrobe": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "story-01": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "story-02": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "story-03": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "story-04": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "story-05": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "story-06": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "story-07": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "story-08": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "story-09": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  },
  "story-10": {
    "width": 1672,
    "height": 941,
    "widths": [
      320,
      480,
      640,
      768,
      1024,
      1440,
      1672
    ]
  }
};
